name: littlehelpbook_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  envied: ^0.5.2
  equatable: ^2.0.5
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_riverpod: ^2.4.9
  flutter_web_plugins:
    sdk: flutter
  geocoding: ^2.1.1
  go_router: ^12.1.3
  intl: ^0.18.1
  intl_utils: ^2.8.7
  latlong2: ^0.9.0
  logging: ^1.2.0
  path_provider: ^2.1.1
  powersync: ^1.1.0
  riverpod: ^2.4.9
  simple_routes: ^1.0.1
  supabase_flutter: ^2.1.0
  url_launcher: ^6.2.3
  vector_map_tiles: ^7.0.1
  wolt_modal_sheet: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
