name: littlehelpbook_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.2
  envied: ^1.1.0
  equatable: ^2.0.7
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3+1
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.8.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_map_marker_cluster: ^1.4.0
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  geocoding: ^3.0.0
  go_router: ^14.7.2
  growthbook_sdk_flutter: ^3.9.9
  intl: ^0.19.0
  intl_utils: ^2.8.9
  latlong2: ^0.9.1
  logging: ^1.3.0
  loggy: ^2.0.3
  package_info_plus: ^8.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  powersync: ^1.11.2
  responsive_builder: ^0.7.1
  sentry_flutter: ^8.12.0
  sentry_logging: ^8.12.0
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_map_tiles: ^8.0.0
  wolt_modal_sheet: ^0.10.0

dev_dependencies:
  analyzer: ^6.11.0
  build_runner: ^2.4.14
  envied_generator: ^1.1.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated
