name: littlehelpbook_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^10.0.0
  intl: ^0.18.1
  intl_utils: ^2.8.4
  path_provider: ^2.0.15
  powersync: ^0.4.0
  riverpod: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
