name: littlehelpbook_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3
  flutter_map: ^6.1.0
  flutter_map_animations: ^0.5.3
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.4
  flutter_map_marker_cluster: ^1.3.6
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  geocoding: ^3.0.0
  go_router: ^12.1.3
  intl: ^0.19.0
  intl_utils: ^2.8.7
  latlong2: ^0.9.1
  logging: ^1.2.0
  loggy: ^2.0.3
  mockito: ^5.4.4
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  powersync: ^1.4.1
  responsive_builder: ^0.7.0
  riverpod: ^2.5.1
  sentry_flutter: ^8.2.0
  sentry_logging: ^8.2.0
  simple_routes: ^1.0.1
  supabase_flutter: ^2.5.5
  uptech_growthbook_sdk_flutter: ^1.2.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  vector_map_tiles: ^7.3.1
  wolt_modal_sheet: ^0.6.1

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated
