#!/usr/bin/env zsh

flavor=${1:-dev}

echo "\nSetting up $flavor flavor..."

# Clean up cache for generated, files, etc.
echo "\n\nRunning fvm flutter clean..."
time fvm flutter clean

echo "\n\nRunning fvm dart pub global activate very_good_cli..."
time dart pub global activate very_good_cli
time export PATH="$PATH":"$HOME/.pub-cache/bin"
time very_good --analytics false

# Update dependencies based on any changes in the pubspec.yaml
echo "\n\nRunning very_good get..."
time very_good packages get --recursive

# Run Build Runner.
echo "\n\nRunning flutter pub run build_runner build..."
time fvm flutter pub run build_runner build -d 

# Generate localization files
echo "\n\nRunning flutter gen-l10n..."
fvm flutter pub run intl_utils:generate

# Make sure format is good
echo "\n\nRunning dart format ..."
time fvm dart format .

# Make sure code is good
echo "\n\nRunning flutter analyze..."
time fvm flutter analyze .

exit 0